export const eventServiceProductNames = {
  cannolis_booth_only: "1 Booth with Server (No Box)",
  cannolis_box_booth: "1 Server with Box + Booth with 1 Server",
  cannolis_box_only: "1 Server with Box Only",
  chocolate_fountains: "Chocolate Fountains",
  churros_cinnamon_sugar: "Churros with Cinnamon Sugar",
  churros_filled_topping_bar: "Churros Filled with Topping Bar",
  churros_topping_bar: "Churros with Topping Bar",
  churros_topping_bar_gelato: "Churros with Topping Bar & Gelato",
  conchas: "Conchas",
  cookies_topping_bar: "Cookies with Topping Bar",
  cookies_topping_bar_gelato: "Cookies with Topping Bar & Gelato",
  donuts_topping_bar: "Donuts with Topping Bar",
  donuts_topping_bar_gelato: "Donuts with Topping Bar & Gelato",
  gelato_topping_bar: "Gelato with Topping Bar",
  mexican_street_corn_bar: "Mexican Street Corn Bar (Esquites)",
  pancakes_topping_bar: "Pancakes with Topping Bar",
  pancakes_topping_bar_fruit: "Pancakes with Topping Bar + Fresh Fruit",
  pancakes_topping_bar_gelato: "Pancakes with Topping Bar & Gelato",
  popcorn_bar: "Popcorn Bar",
  ramen_bar: "Ramen Bar",
  rolled_ice_cream_signature: "Rolled Ice Cream - Signature Rollz",
  rolled_ice_cream_traditional: "Rolled Ice Cream - Traditional Flavors + Fresh Fruits",
  smores_topping_bar: "S'mores with Topping Bar",
  sorbet_topping_bar: "Sorbet with Topping Bar",
  waffles_topping_bar: "Waffles with Topping Bar",
  waffles_topping_bar_fruit: "Waffles with Topping Bar + Fresh Fruit",
  waffles_topping_bar_gelato: "Waffles with Topping Bar & Gelato",
} as const;
