export type EventPayrollLineItemTable = {
  Row: {
    additional_unit_amount_mxn: number;
    calculated_amount_mxn: number;
    created_at: string;
    event_id: string;
    event_staff_assignment_id: string | null;
    id: string;
    included_quantity: number;
    manual_adjustment_mxn: number;
    notes: string;
    overtime_rate_mxn: number;
    paid_at: string | null;
    pay_rule: string;
    payroll_task_id: string | null;
    quantity: number;
    rate_mxn: number;
    scheduled_pay_date: string | null;
    source: string;
    staff_member_id: string;
    status: string;
    task_category: string;
    task_name: string;
    tips_bonus_mxn: number;
    total_mxn: number;
    updated_at: string;
  };
  Insert: {
    additional_unit_amount_mxn?: number;
    calculated_amount_mxn?: number;
    created_at?: string;
    event_id: string;
    event_staff_assignment_id?: string | null;
    id?: string;
    included_quantity?: number;
    manual_adjustment_mxn?: number;
    notes?: string;
    overtime_rate_mxn?: number;
    paid_at?: string | null;
    pay_rule?: string;
    payroll_task_id?: string | null;
    quantity?: number;
    rate_mxn?: number;
    scheduled_pay_date?: string | null;
    source?: string;
    staff_member_id: string;
    status?: string;
    task_category?: string;
    task_name: string;
    tips_bonus_mxn?: number;
    total_mxn?: number;
    updated_at?: string;
  };
  Update: Partial<EventPayrollLineItemTable["Insert"]>;
  Relationships: [];
};
