export type StaffMemberTable = {
  Row: {
    address: string;
    bank_account_number: string;
    bank_beneficiary: string;
    bank_card_number: string;
    bank_clabe: string;
    bank_name: string;
    created_at: string;
    date_of_birth: string | null;
    display_name: string;
    email: string;
    id: string;
    id_back_file_url: string;
    id_expiration_date: string | null;
    id_front_file_url: string;
    id_number: string;
    id_type: string;
    is_active: boolean;
    is_driver: boolean;
    name: string;
    notes: string;
    phone: string;
    updated_at: string;
  };
  Insert: {
    address?: string;
    bank_account_number?: string;
    bank_beneficiary?: string;
    bank_card_number?: string;
    bank_clabe?: string;
    bank_name?: string;
    created_at?: string;
    date_of_birth?: string | null;
    display_name?: string;
    email?: string;
    id?: string;
    id_back_file_url?: string;
    id_expiration_date?: string | null;
    id_front_file_url?: string;
    id_number?: string;
    id_type?: string;
    is_active?: boolean;
    is_driver?: boolean;
    name: string;
    notes?: string;
    phone?: string;
    updated_at?: string;
  };
  Update: Partial<StaffMemberTable["Insert"]>;
  Relationships: [];
};
