export type VenueTable = {
  Row: {
    area: string;
    brochure_behavior: string;
    city: string;
    commission_fixed_amount: number | null;
    commission_model: string;
    commission_notes: string;
    commission_percentage: number | null;
    country: string;
    created_at: string;
    distance_from_hq_km: number | null;
    facebook: string;
    factura_recipient: string;
    fiscal_cfdi_use: string;
    fiscal_default_bank_account_id: string | null;
    fiscal_default_profile_id: string | null;
    fiscal_due_day: number | null;
    fiscal_due_rule: string;
    fiscal_isr_retention_rate: number;
    fiscal_iva_rate: number;
    fiscal_iva_retention_rate: number;
    fiscal_legal_name: string;
    fiscal_notes: string;
    fiscal_payment_form: string;
    fiscal_payment_method: string;
    fiscal_postal_code: string;
    fiscal_retains_isr: boolean;
    fiscal_retains_iva: boolean;
    fiscal_rfc: string;
    fiscal_supplier_number: string;
    fiscal_tax_object: string;
    fiscal_tax_regime: string;
    google_maps_url: string;
    id: string;
    instagram: string;
    internal_status: string;
    invoice_behavior: string;
    is_preferred_vendor: boolean;
    name: string;
    notes: string;
    payment_billing_type: string;
    payment_responsibility: string;
    phone: string;
    postal_code: string;
    quote_pricing_model: string;
    requires_sat_fiscal: boolean;
    settings_notes: string;
    state_province: string;
    street_address: string;
    suppress_client_invoice: boolean;
    travel_time_minutes: number | null;
    updated_at: string;
    uses_sub_locations: boolean;
    website_url: string;
  };
  Insert: {
    area?: string;
    brochure_behavior?: string;
    city?: string;
    commission_fixed_amount?: number | null;
    commission_model?: string;
    commission_notes?: string;
    commission_percentage?: number | null;
    country?: string;
    created_at?: string;
    distance_from_hq_km?: number | null;
    facebook?: string;
    factura_recipient?: string;
    fiscal_cfdi_use?: string;
    fiscal_default_bank_account_id?: string | null;
    fiscal_default_profile_id?: string | null;
    fiscal_due_day?: number | null;
    fiscal_due_rule?: string;
    fiscal_isr_retention_rate?: number;
    fiscal_iva_rate?: number;
    fiscal_iva_retention_rate?: number;
    fiscal_legal_name?: string;
    fiscal_notes?: string;
    fiscal_payment_form?: string;
    fiscal_payment_method?: string;
    fiscal_postal_code?: string;
    fiscal_retains_isr?: boolean;
    fiscal_retains_iva?: boolean;
    fiscal_rfc?: string;
    fiscal_supplier_number?: string;
    fiscal_tax_object?: string;
    fiscal_tax_regime?: string;
    google_maps_url?: string;
    id?: string;
    instagram?: string;
    internal_status?: string;
    invoice_behavior?: string;
    is_preferred_vendor?: boolean;
    name: string;
    notes?: string;
    payment_billing_type?: string;
    payment_responsibility?: string;
    phone?: string;
    postal_code?: string;
    quote_pricing_model?: string;
    requires_sat_fiscal?: boolean;
    settings_notes?: string;
    state_province?: string;
    street_address?: string;
    suppress_client_invoice?: boolean;
    travel_time_minutes?: number | null;
    updated_at?: string;
    uses_sub_locations?: boolean;
    website_url?: string;
  };
  Update: Partial<VenueTable["Insert"]>;
  Relationships: [];
};

export type PlannerTable = {
  Row: {
    area: string;
    city: string;
    company_name: string;
    created_at: string;
    default_commission_model: string;
    default_commission_percentage: number | null;
    email: string;
    id: string;
    instagram: string;
    internal_status: string;
    name: string;
    notes: string;
    phone: string;
    preferred_contact_method: string;
    pv_commission_policy: string;
    updated_at: string;
    website_url: string;
    whatsapp: string;
  };
  Insert: {
    area?: string;
    city?: string;
    company_name?: string;
    created_at?: string;
    default_commission_model?: string;
    default_commission_percentage?: number | null;
    email?: string;
    id?: string;
    instagram?: string;
    internal_status?: string;
    name: string;
    notes?: string;
    phone?: string;
    preferred_contact_method?: string;
    pv_commission_policy?: string;
    updated_at?: string;
    website_url?: string;
    whatsapp?: string;
  };
  Update: Partial<PlannerTable["Insert"]>;
  Relationships: [];
};

export type VenueContactTable = {
  Row: {
    created_at: string;
    email: string;
    id: string;
    is_active: boolean;
    name: string;
    notes: string;
    phone: string;
    preferred_contact_method: string;
    role: string;
    updated_at: string;
    venue_id: string;
    whatsapp: string;
  };
  Insert: {
    created_at?: string;
    email?: string;
    id?: string;
    is_active?: boolean;
    name: string;
    notes?: string;
    phone?: string;
    preferred_contact_method?: string;
    role: string;
    updated_at?: string;
    venue_id: string;
    whatsapp?: string;
  };
  Update: Partial<VenueContactTable["Insert"]>;
  Relationships: [];
};

export type VenueSubLocationTable = {
  Row: {
    created_at: string;
    id: string;
    is_active: boolean;
    name: string;
    notes: string;
    updated_at: string;
    venue_id: string;
  };
  Insert: {
    created_at?: string;
    id?: string;
    is_active?: boolean;
    name: string;
    notes?: string;
    updated_at?: string;
    venue_id: string;
  };
  Update: Partial<VenueSubLocationTable["Insert"]>;
  Relationships: [];
};

export type EventPlannerTable = {
  Row: {
    commission_eligible: boolean;
    commission_percentage_override: number | null;
    created_at: string;
    event_id: string;
    id: string;
    is_primary: boolean;
    notes: string;
    planner_id: string;
    role: string;
    updated_at: string;
  };
  Insert: {
    commission_eligible?: boolean;
    commission_percentage_override?: number | null;
    created_at?: string;
    event_id: string;
    id?: string;
    is_primary?: boolean;
    notes?: string;
    planner_id: string;
    role?: string;
    updated_at?: string;
  };
  Update: Partial<EventPlannerTable["Insert"]>;
  Relationships: [];
};

export type EventVenueContactTable = {
  Row: {
    created_at: string;
    email: string;
    event_id: string;
    id: string;
    name: string;
    notes: string;
    phone: string;
    role: string;
    should_save_to_venue_profile: boolean;
    source_venue_contact_id: string | null;
    updated_at: string;
  };
  Insert: {
    created_at?: string;
    email?: string;
    event_id: string;
    id?: string;
    name: string;
    notes?: string;
    phone?: string;
    role?: string;
    should_save_to_venue_profile?: boolean;
    source_venue_contact_id?: string | null;
    updated_at?: string;
  };
  Update: Partial<EventVenueContactTable["Insert"]>;
  Relationships: [];
};
