import { readFile } from "node:fs/promises";
import path from "node:path";

import { StandardFonts, rgb, type PDFDocument, type PDFPage } from "pdf-lib";

import type { Invoice } from "@/features/crm/invoice/types/invoice";
import type { QuoteSummary, QuoteVersion } from "@/features/crm/quote/types/quote";

export const PAGE = {
  height: 842,
  width: 595,
};

export const MARGIN = 48;

const BEIGE = rgb(0.96, 0.94, 0.91);

export type PdfFonts = {
  bold: any;
  regular: any;
  serif: any;
};

export async function loadFonts(pdf: PDFDocument): Promise<PdfFonts> {
  return {
    bold: await pdf.embedFont(StandardFonts.HelveticaBold),
    regular: await pdf.embedFont(StandardFonts.Helvetica),
    serif: await pdf.embedFont(StandardFonts.TimesRoman),
  };
}

export async function drawHeader(
  pdf: PDFDocument,
  page: PDFPage,
  fonts: PdfFonts,
  title: string,
  subtitle: string,
  metaLine: string | null,
) {
  page.drawText(title, {
    color: rgb(0.11, 0.12, 0.15),
    font: fonts.serif,
    size: 34,
    x: MARGIN,
    y: PAGE.height - 66,
  });

  page.drawText("OH MY DESSERTS & SNACKS", {
    color: rgb(0.11, 0.12, 0.15),
    font: fonts.bold,
    size: 10,
    x: MARGIN,
    y: PAGE.height - 90,
  });

  page.drawText(subtitle, {
    color: rgb(0.32, 0.35, 0.42),
    font: fonts.regular,
    size: 12,
    x: MARGIN,
    y: PAGE.height - 106,
  });

  if (metaLine) {
    page.drawText(metaLine, {
      color: rgb(0.32, 0.35, 0.42),
      font: fonts.regular,
      size: 10,
      x: MARGIN,
      y: PAGE.height - 120,
    });
  }

  const logo = await loadLogo(pdf);
  if (logo) {
    page.drawImage(logo, {
      height: 64,
      width: 164,
      x: PAGE.width - MARGIN - 164,
      y: PAGE.height - 104,
    });
  }

  page.drawLine({
    color: rgb(0.86, 0.88, 0.91),
    end: { x: PAGE.width - MARGIN, y: PAGE.height - 118 },
    start: { x: MARGIN, y: PAGE.height - 118 },
    thickness: 1,
  });

  page.drawText("Document generated by OMDS CRM", {
    color: rgb(0.45, 0.48, 0.55),
    font: fonts.regular,
    size: 8,
    x: MARGIN,
    y: PAGE.height - 144,
  });
}

export function drawQuoteInfo(
  page: PDFPage,
  fonts: PdfFonts,
  quote: QuoteSummary,
  version: QuoteVersion,
  y: number,
) {
  const recipient = quote.recipients[0];
  const leftX = MARGIN;
  const rightX = MARGIN + 290;

  page.drawText("PREPARED FOR", { color: rgb(0.36, 0.39, 0.45), font: fonts.bold, size: 9, x: leftX, y });
  page.drawText(recipient?.name ?? quote.title, { color: rgb(0.12, 0.14, 0.19), font: fonts.bold, size: 10, x: leftX, y: y - 14 });
  if (recipient?.email) {
    page.drawText(recipient.email, { color: rgb(0.36, 0.39, 0.45), font: fonts.regular, size: 9, x: leftX, y: y - 28 });
  }

  const details: Array<[string, string]> = [
    ["QUOTE #", `V${version.versionNumber}`],
    ["STATUS", quote.status.toUpperCase()],
    ["VALID UNTIL", formatDate(version.expiresAt)],
    ["CURRENCY", version.displayCurrency.toUpperCase()],
  ];

  let detailY = y;
  for (const [label, value] of details) {
    page.drawText(label, { color: rgb(0.36, 0.39, 0.45), font: fonts.bold, size: 8, x: rightX, y: detailY });
    page.drawText(value, { color: rgb(0.12, 0.14, 0.19), font: fonts.regular, size: 9, x: rightX + 90, y: detailY });
    detailY -= 14;
  }

  return y - 74;
}

export function drawInvoiceInfo(page: PDFPage, fonts: PdfFonts, invoice: Invoice, y: number) {
  const leftX = MARGIN;
  const rightX = MARGIN + 290;

  page.drawText("INVOICE TYPE", { color: rgb(0.36, 0.39, 0.45), font: fonts.bold, size: 9, x: leftX, y });
  page.drawText(invoice.invoiceType.replaceAll("_", " ").toUpperCase(), {
    color: rgb(0.12, 0.14, 0.19),
    font: fonts.bold,
    size: 10,
    x: leftX,
    y: y - 14,
  });

  const details: Array<[string, string]> = [
    ["INVOICE #", invoice.id.slice(0, 8).toUpperCase()],
    ["STATUS", invoice.status.replace("_", " ").toUpperCase()],
    ["ISSUED", formatDate(invoice.issuedAt)],
    ["DUE", formatDate(invoice.dueAt)],
  ];

  let detailY = y;
  for (const [label, value] of details) {
    page.drawText(label, { color: rgb(0.36, 0.39, 0.45), font: fonts.bold, size: 8, x: rightX, y: detailY });
    page.drawText(value, { color: rgb(0.12, 0.14, 0.19), font: fonts.regular, size: 9, x: rightX + 90, y: detailY });
    detailY -= 14;
  }

  return y - 74;
}

export function drawItemsHeader(page: PDFPage, font: any, y: number, showPrice: boolean) {
  page.drawRectangle({ color: BEIGE, height: 18, width: PAGE.width - MARGIN * 2, x: MARGIN, y: y - 3 });
  page.drawText("DESCRIPTION", { color: rgb(0.33, 0.35, 0.42), font, size: 9, x: MARGIN + 8, y: y + 2 });
  page.drawText("QTY", { color: rgb(0.33, 0.35, 0.42), font, size: 9, x: PAGE.width - MARGIN - 170, y: y + 2 });
  if (showPrice) page.drawText("PRICE", { color: rgb(0.33, 0.35, 0.42), font, size: 9, x: PAGE.width - MARGIN - 120, y: y + 2 });
  page.drawText("AMOUNT", { color: rgb(0.33, 0.35, 0.42), font, size: 9, x: PAGE.width - MARGIN - 68, y: y + 2 });
  return y - 22;
}

export function drawItemLine(page: PDFPage, fonts: PdfFonts, y: number, description: string, quantity: string, amount: string) {
  page.drawText(trim(description, 56), { color: rgb(0.14, 0.16, 0.2), font: fonts.bold, size: 10, x: MARGIN + 8, y });
  page.drawText(quantity, { color: rgb(0.14, 0.16, 0.2), font: fonts.regular, size: 10, x: PAGE.width - MARGIN - 170, y });
  page.drawText(formatCurrency(amount), { color: rgb(0.14, 0.16, 0.2), font: fonts.bold, size: 10, x: PAGE.width - MARGIN - 68, y });
  page.drawLine({ color: rgb(0.93, 0.94, 0.96), end: { x: PAGE.width - MARGIN, y: y - 6 }, start: { x: MARGIN, y: y - 6 }, thickness: 1 });
  return y - 18;
}

export function drawTermsBox(page: PDFPage, fonts: PdfFonts, text: string) {
  const x = MARGIN;
  const y = 180;
  const width = 282;
  const height = 88;

  page.drawRectangle({ borderColor: rgb(0.89, 0.9, 0.92), borderWidth: 1, color: rgb(1, 1, 1), height, width, x, y });
  page.drawRectangle({ color: BEIGE, height: 20, width, x, y: y + height - 20 });
  page.drawText("TERMS & CONDITIONS", { color: rgb(0.3, 0.34, 0.41), font: fonts.bold, size: 8, x: x + 10, y: y + height - 14 });
  page.drawText(trim(text, 116), { color: rgb(0.35, 0.39, 0.46), font: fonts.regular, size: 8, x: x + 10, y: y + height - 32 });
}

export function drawTotals(page: PDFPage, fonts: PdfFonts, totals: { items: string; subtotal: string; tax: string; total: string }) {
  const panelX = PAGE.width - MARGIN - 210;
  const panelY = 180;
  const panelW = 210;
  const panelH = 88;

  page.drawRectangle({ borderColor: rgb(0.89, 0.9, 0.92), borderWidth: 1, color: rgb(1, 1, 1), height: panelH, width: panelW, x: panelX, y: panelY });
  page.drawRectangle({ color: BEIGE, height: 20, width: panelW, x: panelX, y: panelY + panelH - 20 });

  const xLabel = panelX + 12;
  const xValue = panelX + panelW - 68;
  const start = panelY + panelH - 34;

  drawTotalRow(page, fonts.regular, xLabel, xValue, start, "Items", totals.items);
  drawTotalRow(page, fonts.regular, xLabel, xValue, start - 14, "Subtotal", totals.subtotal);
  drawTotalRow(page, fonts.regular, xLabel, xValue, start - 28, "Tax", totals.tax);
  drawTotalRow(page, fonts.bold, xLabel, xValue, start - 46, "Amount Due", totals.total);
}

export function drawSignatureRow(page: PDFPage, fonts: PdfFonts) {
  const startY = 116;
  const blockW = 156;
  const gap = 18;

  for (let i = 0; i < 3; i += 1) {
    const x = MARGIN + i * (blockW + gap);
    page.drawLine({ color: rgb(0.7, 0.72, 0.76), end: { x: x + blockW, y: startY }, start: { x, y: startY }, thickness: 1 });
    page.drawText(i === 0 ? "Name" : i === 1 ? "Signature" : "Date", {
      color: rgb(0.45, 0.48, 0.55),
      font: fonts.regular,
      size: 8,
      x,
      y: startY - 12,
    });
  }
}

export function drawThankYou(page: PDFPage, fonts: PdfFonts) {
  page.drawRectangle({ color: BEIGE, height: 16, width: PAGE.width - MARGIN * 2, x: MARGIN, y: 72 });
  page.drawText("THANK YOU FOR YOUR BUSINESS", {
    color: rgb(0.36, 0.39, 0.45),
    font: fonts.regular,
    size: 8,
    x: MARGIN + 170,
    y: 78,
  });
}

function drawTotalRow(page: PDFPage, font: any, xLabel: number, xValue: number, y: number, label: string, value: string) {
  page.drawText(label.toUpperCase(), { color: rgb(0.37, 0.4, 0.46), font, size: 9, x: xLabel, y });
  page.drawText(formatCurrency(value), { color: rgb(0.12, 0.14, 0.19), font, size: 9, x: xValue, y });
}

function trim(value: string, max: number) {
  if (value.length <= max) return value;
  return `${value.slice(0, max - 1)}...`;
}

function formatCurrency(value: string) {
  return new Intl.NumberFormat("en-US", { currency: "MXN", style: "currency" }).format(Number(value || 0));
}

function formatDate(value: string | null) {
  if (!value) return "Not provided";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "Not provided";
  return new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(date);
}

async function loadLogo(pdf: PDFDocument) {
  try {
    const logoPath = path.join(process.cwd(), "public", "branding", "ohmydesserts-logo-color.png");
    const file = await readFile(logoPath);
    return pdf.embedPng(file);
  } catch {
    return null;
  }
}
